{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "API 1.0.0",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "servers": [
    {
      "url": "https://project-pets-api.herokuapp.com/"
    },
    {
      "url": "http://localhost:3005"
    }
  ],
  "tags": [
    {
      "name": "UserAuth",
      "description": "Authorization and info endpoints"
    },
    {
      "name": "Notice",
      "description": "Notice endpoints"
    },
    {
      "name": "Pet",
      "description": "Pet endpoints"
    },
    {
      "name": "Sponsors-info",
      "description": "Sponsors-info endpoints"
    },
    {
      "name": "News",
      "description": "News endpoints"
    }
  ],
  "paths": {
    "/users/register": {
      "post": {
        "tags": [
          "UserAuth"
        ],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "409": {
            "description": "Email in use",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "UserAuth"
        ],
        "summary": "User authentication",
        "parameters": [],
        "requestBody": {
          "description": "Authentication's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email doesn't exist / Password is wrong",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/logout": {
      "get": {
        "tags": [
          "UserAuth"
        ],
        "summary": "Logout",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/refresh": {
      "post": {
        "tags": [
          "UserAuth"
        ],
        "summary": "Refresh Tokens",
        "security": [
          {
            "Bearer": []
          }
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserRefreshTokensResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/users/info": {
      "get": {
        "tags": [
          "UserAuth"
        ],
        "summary": "Get current user info",
        "parameters": [],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserInfo"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized (invalid access token)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/notice/category": {
      "get": {
        "tags": [
          "Notice"
        ],
        "summary": "Get list of categories",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetAllNotice"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": [
          "name",
          "email",
          "password",
          "city",
          "phone"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "format": "name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "example": "Kiev"
          },
          "phone": {
            "type": "string",
            "description": "User's phone",
            "example": 3809739345679
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "city": {
            "type": "string",
            "description": "User's city"
          },
          "phone": {
            "type": "string",
            "description": "User's phone"
          },
          "birthday": {
            "type": "string",
            "description": "User's phone"
          },
          "userImgUrl": {
            "type": "string",
            "description": "User's phone"
          },
          "userPets": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "ownNotices": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "favoriteNotices": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "data": {
            "type": "object",
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "User's accessToken"
              },
              "refreshToken": {
                "type": "string",
                "description": "User's refreshToken"
              }
            }
          }
        },
        "example": {
          "name": "One",
          "email": "1@gmail.com",
          "city": "Kiev",
          "phone": 3809739345679,
          "birthday": null,
          "userImgUrl": null,
          "userPets": [],
          "ownNotices": [],
          "favoriteNotices": [],
          "data": {
            "accessToken": "xxxxx.yyyyy.zzzzz",
            "refreshToken": "xxxxx.yyyyy.zzzzz"
          }
        }
      },
      "LoginRequest": {
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "city": {
            "type": "string",
            "description": "User's city"
          },
          "phone": {
            "type": "string",
            "description": "User's phone"
          },
          "birthday": {
            "type": "string",
            "description": "User's phone"
          },
          "userImgUrl": {
            "type": "string",
            "description": "User's phone"
          },
          "userPets": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "ownNotices": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "favoriteNotices": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AddPetRequest"
            }
          },
          "data": {
            "type": "object",
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "User's accessToken"
              },
              "refreshToken": {
                "type": "string",
                "description": "User's refreshToken"
              }
            }
          }
        },
        "example": {
          "name": "One",
          "email": "1@gmail.com",
          "city": "Kiev",
          "phone": 3809739345679,
          "birthday": null,
          "userImgUrl": null,
          "userPets": [],
          "ownNotices": [],
          "favoriteNotices": [],
          "data": {
            "accessToken": "xxxxx.yyyyy.zzzzz",
            "refreshToken": "xxxxx.yyyyy.zzzzz"
          }
        }
      },
      "UserRefreshTokensResponse": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "accessToken": {
                "type": "string",
                "description": "User's accessToken"
              },
              "refreshToken": {
                "type": "string",
                "description": "User's refreshToken"
              }
            }
          }
        },
        "example": {
          "data": {
            "accessToken": "xxxxx.yyyyy.zzzzz",
            "refreshToken": "xxxxx.yyyyy.zzzzz"
          }
        }
      },
      "GetUserInfo": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "balance": {
                "type": "number",
                "description": "User's balance"
              }
            }
          }
        },
        "example": {
          "name": "One",
          "email": "1@gmail.com",
          "city": "Kiev",
          "phone": 3809739345679,
          "birthday": null,
          "userImgUrl": null,
          "userPets": [],
          "ownNotices": [],
          "favoriteNotices": []
        }
      },
      "AddPetRequest": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "balance": {
                "type": "number",
                "description": "User's balance"
              }
            }
          }
        },
        "example": {
          "name": "One",
          "email": "1@gmail.com",
          "city": "Kiev",
          "phone": 3809739345679,
          "birthday": null,
          "userImgUrl": null,
          "userPets": [],
          "ownNotices": [],
          "favoriteNotices": []
        }
      },
      "---GetUserInfo": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "balance": {
                "type": "number",
                "description": "User's balance"
              }
            }
          }
        },
        "example": {
          "name": "One",
          "email": "1@gmail.com",
          "city": "Kiev",
          "phone": 3809739345679,
          "birthday": null,
          "userImgUrl": null,
          "userPets": [],
          "ownNotices": [],
          "favoriteNotices": []
        }
      },
      "GetAllNotice": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "notice": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "birthday": {
                  "type": "string"
                },
                "breed": {
                  "type": "string"
                },
                "location": {
                  "type": "string"
                },
                "sex": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "price": {
                  "type": "string"
                },
                "imageUrl": {
                  "type": "string"
                },
                "userEmail": {
                  "type": "string"
                },
                "userPhone": {
                  "type": "string"
                },
                "owner": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                },
                "__v": {
                  "type": "number"
                }
              }
            }
          },
          "category": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "success": true,
          "message": "found notice data with this user ID",
          "notice": [],
          "category": [
            "lost-found",
            "for-free",
            "sell"
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
